name: coverage

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Create Docker Container
        run: |
          docker build . -t ci-image
          docker run --interactive --detach \
            --volume ${{ github.workspace }}:/app \
            --env CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} \
            --name ci ci-image

      - name: Install Dependencies
        run: docker exec ci composer update --no-interaction --no-ansi --prefer-dist

      - name: PHPUnit
        run: docker exec ci vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Code Coverage
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
